[package]
name = "realtime-macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enigo = "0.3.0"
rdev = "0.5.3"
# slint = "1.8.0"
# windows = "0.58.0"

[build-dependencies]
slint-build = "1.8.0"
